[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "lib-nn-python3"
version = "0.1.0"
authors = [
  { name="RDLEND", email="rdlendalt@gmail.com" },
]
description = "Neural Network Basics"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
[project.urls]
Homepage = "https://github.com/RDLEND/nn"
Repository = "https://github.com/RDLEND/nn"
Issues = "https://github.com/RDLEND/nn/issues"
